name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy whenever there’s a push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the same Node version as your local setup

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run nx build-storybook ui-library

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/storybook/ui-library  # Path to the generated Storybook files
